### PR TITLE
Fix/terminal restart on default model change

### LINKED ISSUE #55: Restarting App Doesn't Restart The Backend
When you select new default models and restart the app, the terminal process ends but doesn't restart again when the app launches for the second time. This can cause confusion for developers and needs to be fixed.

### PR DESCRIPTION
**Pull request by MarlenaMakosza**
Closes #55

### CODE REVIEW

File: dev-runner.js [hunk 1]
```diff
@@ -0,0 +1,65 @@
+import { spawn } from 'child_process';
```
Comment (czhou578) [inline dev-runner.js]: Could you explain the reason behind removing the npm run build command in `package.json` and putting that logic into this script?

Comment (MarlenaMakosza) [reply dev-runner.js]: When I tried using electronmon/nodemon, closing the app with the X button left the monitor running and waiting for further actions. As a user, I had to manually stop it with Ctrl+C, which I don’t think is a good solution.

My script detects when the user changes the default model and restarts the app, but when the application exits normally, it disables terminal activity.

Also, npm run build is located in dev-runner.js on line 18.
